platform :ios, '8.0'
inhibit_all_warnings!
target 'UCloudMediaRecorderDemo' do
  pod 'UCDLive_iOS',    :path => '../lib'
  project  'UCloudMediaRecorderDemo.project'
  
  post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "!!!! #{target.name}"
  end
  end
end

